### ISSUE TITLE
Game crash

### ISSUE THREAD

**Issue by LyzN16** [yairm210/Unciv#12587]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Game Version

4.14.13

### Describe the bug

When I attack enemy units, game crashes. 

### Steps to Reproduce

When attacking barbarians

### Link to save file

**Platform:** Android
**Version:** 4.14.13 (Build 1.080)
**Rulesets:** [Civ V - Vanilla, Civ V - Gods & Kings]
**Last Screen:** `com.unciv.ui.screens.worldscreen.WorldScreen`

--------------------------------

Device Model: RMX3636
API Level: 33
System Memory: 7693 MB
    Available (used by Kernel): 2498 MB
    System Low Memory state: false
    Java heap limit: 512 MB
    Java heap free: 10 MB

--------------------------------

**Message:**
```
java.lang.IndexOutOfBoundsException: index can't be >= size: 1 >= 1
	at com.badlogic.gdx.utils.Array.get(Array.java:155)
	at com.badlogic.gdx.scenes.scene2d.Group.getChild(Group.java:430)
	at com.unciv.ui.screens.worldscreen.bottombar.BattleTableHelpers$battleAnimation$getMapActorsForCombatant$1.invokeSuspend(BattleTableHelpers.kt:160)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlin.sequences.SequenceBuilderIterator.hasNext(SequenceBuilder.kt:129)
	at kotlin.sequences.SequenceBuilderIterator.yieldAll(SequenceBuilder.kt:172)
	at kotlin.sequences.SequenceScope.yieldAll(SequenceBuilder.kt:92)
	at com.unciv.ui.screens.worldscreen.bottombar.BattleTableHelpers$battleAnimation$actorsToFlashRed$1.invokeSuspend(BattleTableHelpers.kt:166)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlin.sequences.SequenceBuilderIterator.hasNext(SequenceBuilder.kt:129)
	at com.unciv.ui.screens.worldscreen.bottombar.BattleTableHelpers.battleAnimation(BattleTableHelpers.kt:253)
	at com.unciv.ui.screens.worldscreen.bottombar.BattleTable.onAttackButtonClicked(BattleTable.kt:308)
	at com.unciv.ui.screens.worldscreen.bottombar.BattleTable.access$onAttackButtonClicked(BattleTable.kt:38)
	at com.unciv.ui.screens.worldscreen.bottombar.BattleTable$simulateBattle$3.invoke(BattleTable.kt:278)
	at com.unciv.ui.screens.worldscreen.bottombar.BattleTable$simulateBattle$3.invoke(BattleTable.kt:277)
	at com.unciv.ui.components.input.ActivationActionMap.activate(ActivationActionMap.kt:57)
	at com.unciv.ui.components.input.ActorAttachments.activate(ActorAttachments.kt:42)
	at com.unciv.ui.components.input.ActivationExtensionsKt.activate(ActivationExtensions.kt:17)
	at com.unciv.ui.components.input.ActivationListener.tap(ActivationListener.kt:15)
	at com.badlogic.gdx.scenes.scene2d.utils.ActorGestureListener$1.tap(ActorGestureListener.java:52)
	at com.badlogic.gdx.input.GestureDetector.touchUp(GestureDetector.java:206)
	at com.badlogic.gdx.scenes.scene2d.utils.ActorGestureListener.handle(ActorGestureListener.java:125)
	at com.badlogic.gdx.scenes.scene2d.Stage.touchUp(Stage.java:354)
	at com.unciv.ui.screens.basescreen.UncivStage.access$touchUp$s80204510(UncivStage.kt:17)
	at com.unciv.ui.screens.basescreen.UncivStage$touchUp$1.invoke(UncivStage.kt:87)
	at com.unciv.ui.screens.basescreen.UncivStage$touchUp$1.invoke(UncivStage.kt:87)
	at com.unciv.ui.crashhandling.CrashHandlingExtensionsKt$wrapCrashHandling$1.invoke(CrashHandlingExtensions.kt:17)
	at com.unciv.ui.screens.basescreen.UncivStage.touchUp(UncivStage.kt:87)
	at com.badlogic.gdx.backends.android.DefaultAndroidInput.processEvents(DefaultAndroidInput.java:423)
	at com.badlogic.gdx.backends.android.AndroidGraphics.onDrawFrame(AndroidGraphics.java:503)
	at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1605)
	at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1284)

```
**Save Mods:**
```
[Civ V - Gods & Kings]
```

**Save Data:**
<details><summary>Show Saved Game</summary>

```
H4sIAAAAAAAA/+2d65LctnLHX2Uzn86pLB3eL/omryNLOZa18cpHSbn0gTPD1TKeHW44M7L3uPQ2eYG8QioPFoB3cgEQfwAcKccuqWwNLyBIgt2/bjS6f1ut05L8zdP9YfXst1W236T3D/fZ/kh+/vTbalOc9sdt8ct+9Sy4XD0Uh/yYF3t65K+rZ5ZjX64e6f+dT5erw0P6yz7b/rjP6bn2p8vR2dH4bHJWMHtO+OSKTn09f/ZURmej6txE4dSkOjOaPdNnPCG37rGncLN+fep8j6On1w2bF8N6yO/Jtk3+Md/lf0vpOc2bzj9ekX8fy9Om2fhbfdz36X22erb6uh8nl6vs8ECOST9kr1P637I+OPv1YVeU2faH7EPdFbLtQ7HbZvvnH7JqeB2OdP/L9OEh32cHssmP6TFllh6vs+Jhl9GDHoqcDL8XRfl99uvxW7rv22yflenuit5ydbFVtfmi2b565tr2p0/0KezyTZ41ff/PU3Y4jjpYZrucdm288ZTvD6Mtx2xzRy9C/3/4ITtkabm5y7bkMa2efyjzzWl3PJXZij7Hj/mG3NLj4PTq3ZB3kbWP9fg4fa6r9SnfHb8m/9nm+w/0uNV1uks3pEnyxAcH/+spO2V097ui/Jk0T3efypJ8ncMmXx1+PGTlTXZcPSObsstVvr8uC/JQD4cnV24aIg+MPi9yrX22OWbbt8VV+pAf093NMT2eyJEr2tLwRXdvmAyAZpw1z+GmeqfkVZL9t7v0w+GqH5m/rcjjK07lJvsmu0/35CjXpYeRI+itX+UfyaVeEZlDLpWTvStnvblNvXhrubfexvI3642VJrFjBbaX3G6CKLXDNT328KYkb3JPxkTd7/bWd8UmHX305Gr7egBfnf62KVZ0kDycdt1Bt0Wxbe8gHgyRZiTku+Y9No3V/4ibr6v9XX9t3c9osjsa7w67Zj6RF/oLfSPbt6MLkR10Vz2MruhQp91zLmc/0uZRbnPyId6nm0d6h6/zXVrdarP1mG9eF9v8Ns/Kakj8Oxnehze31xkdgM+cr6jI6A/tBkS9/3JVHO+y8qq7Yt06HUySMmG1Lo7H4v6H/MPdsZOSjahz6Bs4Fg/fZbfdvmaX+6kRJkRA2/NixTYpVu7Swz9/zMo3VIryxl16ON5k2f7V/UNZfMyoAqXt/Ym8e/vPdPARMXCxyarrXJLNRC9Y3p+HYvWiV70rOmiLI3lF9WA+fFd8qMbGaGMtXsjQ+EAEEGnpm+6lUwn2K7n+6qfq7by/IDdw8SH/mO0vToeLn/7Rsy/+57+e747/+99kH9n1S3aRltkFebEXt3l5OF7cp/9RlBdkWF0ci4v7LDvSfff0u9vUF17RYfGK/vinb+k7IYM13fS9+q75Cp9v2s9s+l025OB/+kTV0dx9vMvILXzM6COq31W2vWju7R+GvaoH4+XqDR2jdff61lT76FV9JGcTYbdvPmPVF5EfLtLbMs23F8XtxSMRjBf3RA0f0/Lx4qH4JSuXvxv6xMkNdA31J3A+7MGtu+xbb+7xLRk+dJhbdGxk9AZ/epnui7wefmvycVxsiUIui8dsO7rP6qjpfR7WRF1QZFkNOuDRfz7s0sesfPv4QHv58nRfPaOB5m/10pvb78hHGb8lZ9LLOJf1H7v+Qxo63BWn3fbNQ7a/pmc/XuebSjfWX3QtU64aXV9pN/Jp/5rfk1sciNXV9xmRZOuipFh0k6f3ZNOLlH7kV9mO8lbz66/pbpcdj2m3gQiZov9VPwPSWrGnQvYv6fq0o2JjVxzo71dEXfYH3+Rb+sqavTqkcyCv6vAyp/da3ZRDWr1x/e+dK/c6+DZ4G71w45eO/c55bpPruqO9vk13J/1ub7w7mOz2x22Pzx5Q14G8x/1m+vr8y/pP//oqOnvVoQ499fk+v093Fy9P1eiht+SETcsijmuOeFu0x1RHTNt6X+kmIvObMUE0CdHFR/LkDxWrnwkFXxf7U6Uk3gtBrzvsM6JexEA9Oo4b1kuTTZyuN4kVudut5Sexa6WuF1lOuPVtLwgD37EB1uvEdUd832S7u1yH+PomB3ag2/xynEagXg6Pdcc//fHB45Y8Dv915ypTYP2URxjYCA1ZDIQgsG4bgECE5Tz3zCx3fl1SYXsr3VvF0sp6GZUyVEJSimWsSPrTTSoTm44M/3v7yr62v7Xf2lSXtMqgVjTuWNHEIz3T7nTs8V5vtLdVM7FBNXJNLJRMT3u0TXwhSqP3H8j4BvzPpDC8p76Bavi3vgHP9l03ta3Yd3yiL5LIStwosvwwdKLEDuLkdgvoi9ozV7kuG31xc/r5jki2VKwzfLHO6JsdeCwdu/np1T9bLeGO97rjvR6zKYejNbqTFbVG86hRCe5+gdb4FyXBJe2AoQgXCm22LUB/nVd4U5J3rkOBlUD3ttKbYSVUu4MFzIDfufwmd/3FAH89+BsBvs7iNAvdwNoGm9Tyt8GttY5uXcv1svXmNvDX7u0Gce46g9mnRoT/M7n0+lR+uBOKcCphhZ7eQcv1hmYapxbN1b9amd0d60432N2xT5phyvB2j5r4bp/0CPp7aSPJ/Tbo/u0uoAL/fvh7VR1kZD4832VlM8t6rJ1ZL6jzlYqXdHMkj/pjujuNn/F7RbthoHRajxJgJXxJCse79r/1uQqH7o25+obuddzR7j/0jQl74bM5mEKGvUBHZ6NvvGi9tVM3tm792LV8e+tbqROG1ibZJJlj21lgB4C+8dppvM5eaC6m7F/yRhODrQLxR44kb2QMjI9xxnYDzzDgq5TjY+Ws/3Gfk++48rYTCVEcDunm55WMxVDf/0jlNNJiET9T3baKqqFxGL9PVcPQF60OUPE0AZMXY+1hxsf0xyTB35O94D+R391Ia0R4EGdpbPtrK4rdxPKDTWatU8+x4jRyN0lKpXsIiPCkjx/bTwBWx17om61+NuEhwXgqwBo7/7vdyXhve/SkMZ8j3LvG5mT8NZG/5O3tKlGwelGS72e7e1zxtMDrfH86ZvXk6pweGDzDkSpohMhCpkfd+h/K4FyTDhqWw3iO3Iz98HfC7bMfp/jTa2MnjAVkeonJgb8nnzD5/a7Yb6tv/ica71QSaZ+VF1dleqx11DhskzVIm9HVxVzUP5th2vxqx2nzczg7Vm/pPK3jodr87MZq23YzNUZ/mhin2sPrD3QYThU5T9Chfp9tbEEQuFmy9qyNnWwsP76NrHRtb6wkTKMwzjw/cxFusJr5eyvuyaG9nno86aDRcbR40m1oYKCLPG1PSaYboukpTxrlRpsODoAY4lVZVred7iQEVfu0YF39u/URnt9wW8bRZ0BRExgln7mOnm5a+P9onn029xpDxrYhqZWM3SbBOsn8W2ubxETGBlvbWsduaNnrjR8m69BdZ8h8fB+h2onY9nIaInYchmVN4rCs2nwKJsLTm/wOxodPW+PZZv3pCwrW9hlNnHAbwAc3Z3g9HSrfV0HA2fZ5FcxMmqDv4YmzbvOHr05b5C8aXrzk/M7fiX1mVvDfbIrTXORufcxn9MoFT8R+PZhatI4d93bjppYTBq7lZxvfijPHsUJ7HbnuZr1Zb2N8Fr9aqdiI/fZyGmK/a3M47+74zYy80y3BcgY7Br/D9sBpCwFn4p6cgcn4l8WBdnnof2tfBJW8Bfn/Ls1lvG/t01qArMPfjZgVeMGGEnhG6P4hZnEx269pva4W9qy6VYzNZnov5Psoj29zOt6dyPP82IkdL4kDMjrJR/CKiiXXi4PAIXLIc5zI8m3fs9brLLXscBsmYZy4Tkgtfnr8dVqS/x4bGCJcdFvdHv0sr+7y7PZYf3j1QqP6E2csOiKSofn7vrsxesChFvTkdVQLpeioqR5GRXPfFPdk2Fci7bJdhHWsDqrujj6/uzomor7latmTXa8vpJ55equRU4u71+kD7f99+jC+oU0tfd7lx7u/kk3VZ7/yv3LIX+/iT5W6unC+smP7z+Sy5Oyb/G/Vl32X1Wsy3aQH8Gybn2hUaJmSfxzqaM9f8u2RvHW/WoWfVWKufidR4MeBQ7/ItHpOPxDNle4/EBlORzyRmrvtu5J2mn6ajcz+jtxt9YTX6SF7mxHyzWl332yyhvzH69q9ZjVoUOlnuXMa90YV1ix7TuNVcT3Jc6qDXfkLtO078qe0t2HLn9I8LSeRP6VfiSt9StCcEsmf0qYnCOVPaRdVA2++XaYNvPhmOs2Rfe+DCTsHef19gKH8OW3wIDAAHK91F8qf4rfeQPlTgtYHKX9KMwKAAeBE7VSn/Cnd5Kn8Kd10rPyHafdL1GVPad8/cArSfBtYJH9GG3Qkf0bQro6WFqqegiB2QUE8FN6yd4NKYgeXxC4uiT1cEvu4JA5wSRzikjjCJXGMS+JEQRDbCoLYURDELi6IPVwQ+7ggDnBBHOKCOMIFcQwL4lZ2I1LMxgUxJLRhQezBgthHBXEjuhEx7CuIbk9BdLug6B6Ke9mnjMpuB5fdLi67PVx2+7jsDnDZHeKyO8Jld4zL7kRBdNsKotvBRbeLi24PF90+LroDXHSHuOiOcNEdw6K7lfaIcEWIzYFFtwuLbg8W3X43R3qsj32R0Rir2uv0alO5kFChrsLwiIB2QQE9FOqybwyV0A4uoV1cQnu4hPZxCR3gEjrEJXSES+gYl9CJgoC2cQHt4ALaxQW0hwtoHxfQAS6gQ1xAR7iAjmEBDTGWDQtoBxbQLiygPXMCuhH2gRFhHygIe19B2HsKwl7BtW2hVI5KeweX9i4u7T1c2vsCaX9VpIcjX0EA7z7EpX0kkPacjsW4tE9wYW/jwt7Bhb2LC3sPF/Y+LuwDXNiHuLCPcGGPvJAEFvY2LOwdWNi7BoW9t4CwRwS3ryC4PQXBreAKt1BaRyW3g0tuF5fcnoTkHq2YIdvrUJpq1UxWXvyQZbd8jcAauTMagTVAOKeEuHiPOvFO41m66KYX+eFuheoI1nDhnJG08l7jqv3KC/lTHFwDuLgG8HAN4OMaIMA1QIhrAOQTjVEN4CSwBrBhDdBGgKM6w4icb3QGMODawhCQZggUNIOvoBkUwlUsBU+7haI9qhocXDW4C6kGD1cNvkA1fFumh8OOhglXocnHfF+lGLa5+oU1ZK5pYOthroWQrTteFuUhoye3257f07jTJjMKopVYo0z6/mKminn1kSYzkr7jNjb360f66XfRpO95Ci1iy4wXpI3DkSU2ZnQbMqQdvqLiXcXFFZWHKyofV1QBrqjwOCXIEEIVlZPAisqGFZXTKCpUtamoI0S1BAqqxVdQLQoBOJbCHIGFGh+obnEEumVGHQFqwxOoDSn5Nygw9VQC+p0+GQvcstjL6QL9LgSdQlqi9dCAUoqYSukqPR53GUMrocqOo35epyUxrATaB1VzrO8AbqvVcSKFJd+Yw1dlM9oPUWUersp8XJXhc/+QRQershhVZU4CqzIbVmUOqsoa5YcI/qhTfiZ8fqGCWgwU1KLCCgFLIbjJUphNsVDLC51IcXC96Ar04jfZISuPOmrDY+vFm2Odtsb8Bf1FtWDA14LGVCxr3KIqNloUQwSaKOarSP498Fu/G+Xf/WmYye37ajEaW0MHTMIg24p0S5d3Uu9En7X4s/R0kEaP3a2FWaZFBkSvubj+93D9j08dQoYyrP8jWP/HqP53Elj/27D+d5T1v21S/0O6PFDQ5aJFJhwdaIni4HjniCbYeOf0pu5YQJXpWnLqp1HvMqdLKdN6xThDPnRYMFbcd1n2wJZNL/PdjjUetLrhcvgB74aUZmuLFEgxzcTze5PvfmZ36V9O+w875rei0al8WMmVXab1ctVW76yTpv7WlOQkx78oymN+W2VwrFexv+7acus8GgGRSffNxtfZfVG2mUbYwFV/1dx977sl21+Xp2OVLbXJsNAqvlH97oK1kdbYPNQdz+mqbvepVh2UJIcc0eYGR9D7OIDBKUscvM8kVHTAQ/ctoImoxb5zXR/FrXgAhtK0Vb2tS0H3sdcmfQdX1R2MP/BxgWY29nJZUoUXVYF2opuus7TcHeTZWxlkEaRzcSrFp3wgnxdMpSFMpRFMpTFKpQ3HIlRqo1TacCxChLFRjo0UODZU4FhR2goeX/Yr7lT5ckjDEzMaC1CyRCEDgNx/+sVbvZdr7OXYE/l4UHYrMS/XMfC5gFeUeANVN0JQEWXrMHohQYoPo9fxe/LSm11Spz4OfxnmCC7+seSuYcLjhIVpGV0GuG5iTz/fne7zfZ0YauLz9GAAVPK2KTouPYhPnx8LyJxwFeYngQDcLu8EMgsppWLE3kXIuQiDFpxGpkEzfD0ynjgIifpJYNCyVUELQqNIgEbs70woiTvUEmET0p4oAc3b035bpjpzPpbPZi35GRvpqSFLFN6vq4EsUUQORntT0dkqJ6bctDh+ynd3RE5OrM6mII8mr8l3r3dcPukEU5y/SQ/5wYSbQTjiBtVfz+arZKMn7KVbAkux2VZ1LD0bGk5dvtSXG9qQLzdi+XL7PEy9L/cdje0uSoY3t300xeTb47Y6hvaiSkY6lX7R5/CpsrSyYajmrM/j3dhr+jToPxWuKEhapRoOhxCiIJsVRwo/YUw4xM2ZaoaU5sVGIRMPesNXM+EZEvAUZwgyxigyNpCJ5CypRwQCjIkCZMaGITPqIBPxkKlgrHywqRzGskaMQYzVZ8sZdWr1K4YWpQcYRN0hiEpQp7HuwLNFVu9j/AIA2TYAyObQ1BGi6SytGWfkM88jC5K86Tbt96QHmR3wdcdfwvN9len+oqpM8PRb6PLNSYWnak1bCPLUya047LLWmaHFeUpkMY9Kc4JEeNLeC569OueiZfsocYo04ajE55DxWEh89QS+dBBfFY9nUlEhQtFVEJiJO7ozS4uGXIhLR36Fjpy3wBon2hbsXSL6y2EwWH9JkA0NEHCf5NCcKpFjblAhaLt6vQHpLqvK1QicudZEjnTP4akGgNd8hMEc3OoxLZenp3kI2LMb4VnHsSBfpiGM1lkFM4PRU2Dlxh4bsVW4AQ+g5xLKrMGiJS591sXLuB5WrVwhXZpQIMbABKDz7omFRlISgdeg02YqNRAEwb3GfG5TyYbglKeOB7O0D7N0ALN0CLN0BLN0jLJ0m8fQTKhk5+9HgggSw/QdC+hbh+YX8qSKyhkYxFQQGs05tixfjI8mfWwCeAUSP4EREKyASq2QUKtzShrGiUcj899c6INXoxgiuiWwy+uxy9AtsbluEaASJNiFiAyMg0YXrbM+SRiOdMYzF7i4PkMMu6b2Yr1DvJ6Gs/5yaEC2zZhjN6yjbVpiVq+0sbHPYKw/h4/nscZL1+A1JhGei2Cei1uek3Z499QmT2B1YWmG6koE8CVFM3XLc0wRd0y2hONPrg99DUE1rjHIjtP14Ug4lb56lgNQVfyTj3f1BagnF21keTjTcbAQMNo5+AdOBRsidgHInXE2vMtc/TmGrCAHtpH2BQmzdcmlS6xtfujwLilIzK3Vbpe9WzcRhO4zXWaRPZdnRa45/lTLgmCa9FwqgXvYzfM6Asc4NQzDhtLPjcoTmq1iCRaEZzx5P14QDK/oi2BvCGNvxMfeGVIGQkOsbsWbAVLuqHsSC98kUNBCVwGYTyaSvsnI+Ht6rZt98YvqleKOi8+C3yJdp43fcl0Jz4a4ojT2OChrUK5gkTfGySyxIOeksjq34xKcJsBPXdCQIV92RsNlgVcHSEehOzz9JMimr8VMXcr9JVa4zXAvOImqC6PgkNS6w6hDUaWFqlpT1PwKBGYAU0C6BhgSfssqnuJpTsHieKxfjXmubCsv6Dll4WoMDZ3iJcgR1gxg1gxx1oxa1kRm2WcpVH6GW45jOiTluFW5+SekcXGuB0nHjtKxN2fxM3tmqVmWbcEJOM6N83BVDyIVyk9wOBSMT8QINdb2H2E8K5eJe5nIx5mvW+hT5WaaNoPS5pypi0fDu3LR8KMSHNx9S0TCM/KgdhdcNumAjBXBonslK+Im31bfzow1sWhY0ZM+MLMteHIjZli8hG3BOHLJFlo6LCaUx211wSfENY+kpiQZ2tvApIFyrJfYElKumCE2chZaziEOblli8qnBR+XMRuIlfECqdgcufdNYGojd4MN2Q4DbDaGK3TBjhHAEJhrqK1MOR8kIEdXMMWLdsMa+cQuGpQYXMExYMklvoiBSsg4kGx8WUTUxp8oxSkCLYhB0yDFRWIIBs0OmdgE3d628Beb2QH+eGXIp++J8nmuDPmuuH34h5SzlLneFgMs12NTAlg3XoHfbyKXBkGjZRz53WX5pIW2f/TL0yK9TZABKTaUoE1MoS8XDTTV6HeHDtjSSTooHFyZGDyZGHyfGgB/VMAOZorxuSrzVF0xST5oFMqPhmAOmte9LZkvoeLMS4I8P9N5pQ8+Px3Tzc7ZdMfwA/UmeCd8Ra1V6fwEQwQYfJv4k9/QK6e5dsd+2nSzz/YesvLgqU3bWqmQxxI0FiGsGnpfi21CJbzF4NhN3zAFplk2OgbTOai+xFHF7gF3MXSaF0J/Pjdsi70Bc/1im+5w59eZ+RmezoAiQEQgVVAxSa386w98ewJzhn4Yg1Ad/lq60tY2W7BCTxLEUDgiJy62WYbimDeD6k4VtNG254pWkjMi2ptMyGcilutAWiVITF1x7QCwfbK4LWCEHgMOvQSV2QScGsshB+O/j+B/w8X/GYgByclhOX2TKsL9YVHfKiFGxsCt3YCcsep2ko97l1kwKYHtSPbUKoVkGkiN+bLK8c9VEcXZLXCYKXs3DYWowJhTDbbAAFOy9Vk+PanUuWqUWePiI+RO5ZKpJjiimSZRDOQ9Ewiu3vKUAU410XTk4lOut7lji16KS+4j5lalQwOTx7GKLZOMOGvXmtr7EfKuhnAdxWMGLt+tM8WXt9QyspJTB9ngqzTiR5uooz4KDmbIiCIZ7OIb7OIYHGhhunJZFBcGMYPhUMrNr3Pbfe/6RfKLpfuS7D3DfvdBLPwrYu8noVDcrYK+9U7aLHkd7KQkl6PT5syUnAyvAxLU5VsYyjvGIGUrOd4z6SyUNa62Syczl1+me/OHkFIaXv3GMGJbfHbNTWKyAGSMaxoIgOhkzN9RTy/LMAm2L48ymxpcC7F4P7GdgcX6RL7kx3Jb8Gn25b3K9qGgm7ytXsJPg/cVm3/i1x/S1T8KCSs4aLv2rNXo20fd3zdQ0QYDUxYHUw4HUh4G0ZVggWbPliIqPzYKvqHNa4Gs8fqYv27UIknU8yBpH5pBvieoDUrHRojgGhXl8DhSCNrEk74Qwc0FVsKyAT2RwGhEsBJdDdpM5WbCKCgf2gOgADuxhuDa4gZdFecgODN3OWPeCIRLT3TxJ0vDiVHKsASPr4XjhEku40/mVtMBUy1rDlF9rS7qJtvjWmaoF8St3GcS1Jcq8mMI9xMNn40Dl4EDl4kDl4UDlawCVyHfHBSq5SnkqlRc6tFImoL+k69NOnrSUSUjyOrYSEnEjYOSumvBnsiVpJFZCHW688DQWuDrw4ibfpzljnEXa7idBYXfJFgI+6WDhr5qxlSZciBLL5rElcoJQSfleTQBGYdXYxNMGO7nlXiS/qpH0vbb1jBRXSUtfh18FSW7U82sigdhkMIszk6lYkINU2AUD3uVmJNpKTAs0nfBpZQZwEFpxcFpxcVrxYFppAQfIcms5gQBwZqlI5NjhUpEorSxLi4vwRxNLGH71lhw4lSsHVdElZNTY/143feYO24MZuid9WWQ5KfetJS0s6eKWBvFE2sSjXbzcCpjEY3R1OgeyZsqYc4AImEV7QkBLxUj2zh2zk9qPT+sMpbujIY8Rk5i0HDgul2RAGILLxSCkJOnakXeIpffckEAdvw6n4bBjIb3PlWutcq7LL3HE0RiQp7srhyQz98dR6gkfnmZ4C4EnB4cnF4cnTwOeIA4SFeNBOUhUlWdRrHCZHHST7z5Wk7nnwx44qrpjONast1zPpXzQmsA2CWQS11iWJDvNfN9zYMfCMklOiLWxLGqx7ExJTcMe4sw4iwTVgvD6BcZ6pUUnlqtCaSZzLi2aAlO4WJwzMDQ/QYmV35wl8mdJcTrJZ6IYfQmia8iU40vM8DIpra36s0Q6KAHnclxzCquFhdQL0CfAtLxgZ62ZT84Vu2JGUjaIGHSxCT0O+nIkAzeF/AwWI4zrwozbYjFQm8ByQgEWz7I0VHVKVK9HkaVFs+NG2TlmDKYvwGHoMPmTVW1ZwYeox5ktG2uAZmIivCtmsqaRGA8sxA6js7v08DUthXL/XXZ7/CGnltqzY3nKBntGWznIO+NEnOb82LASX3Q1EjTmjU36YwYP4MPdUfgU2lW5+lwMOkeNZVFSrjIlBN6F840utpzW7SDSuJHoqaAhymn8uj4QZDIT+sVQ+n5m/v6uiJBM+v6qM/1iwOrnUx3VNnk24g57aJ1ODMiyghiH5V2BYsgFgCvBnao2DpwODpyuBnACs/g9cALRAh1wKkAijzdFqZPA6XAg3EO2ZXFpHM3iehvKsD2nyuvgFgQXTUjYogvQr4QJhioeCfl8bmy+iufdk6IHJJnPbfKAFLkyUoq7031CgyrqZ7zqxEP2tjzd3u4ygy4y3ZfRZzVcxmdnDdamatG7ARxmxhuaXTKO07k5jl48W0skgYcduj/deI4MLY/c0IYz1CqeeKYFc3jx+bvodsaJhFtUSh9w2LQtIHQ2XPc7++AMEkbopEf93AaMFFCfqVgr8st5xdYKYHskuOlh46aHA5serbUCFNSyHFEdoVkTB1iJ1Zk4QGGFzsIByjd0powopyzPZmE9bLE38ZKzuodPPjyrRjkdhCnybe0YIJgUtlHkepIohTOc1UyIhWbCi11RbC8e6oembfI9KTq+4dYc7yobzE+YNM0sYkijvQ4/QX0zkbbe1EAIRCaKqVhpvTgcj2VZLFjwq7dmOOEfZzBcJqYtL4G7/kwDMP0HI7v64gR+1SPUo8+vhqQ2N8BkBiPB1iht6sRxdLWYkHhlBGvl09+IsRaA1ARnVBtnVEeDUSHcDBVwM1DATUHFnLnVZxOTnBPBIzVOeS6+lmyDhaz/OTqWW9GvjZw8ltVf1mSIKjmIu7CbGYKwmI2OlROGgWfL8CEeQR+x2FEhKEQKBOXsGYx9O4CUuAttj79KrAdKq9LZE9gJWLkVU82QqSci03NUD2NGJ3/mcsALUCyHX6UHU1vLx7y05hATsxTQmT21XSkhYzNeCJpPs3twiypAfdPhbEHRI4iqBZWQVOgcoOoYpuoEh2obhuqWwyHUjVU4XFDmZ47doc4FChwurszDDYJnDxk54u3q9Wgqd9l8pwbCP5AAGnFh3rSqqXu4yfeb7O2p3N+QncdqlnbYZY9OxjaHviUsRY+s9MFdlu6Od+QrbOd8E7BOgMcKChzulYkLbO60GP8kwHpf0FYPtNl/u65nmrkWz9QwadeqLmWZ8O4ZREGta7bFBXSHPmzYKFs0iziTF7AhonPaECEzZqYewEtZLKqhY6jpIjIL1BdItFktlBtQCgtH85dwFtkYvyJO9ainmV87aLalp5UNqiBwUYUFe/LZNYHiWmYB0g1vAO/z3dCh8a72kfHQc4kSSQjnA3wewXwew3ye4Hhuq+M5RNqRAmmHfNKeo3PRQ4O8FoJaNQboXM8frVQGSjH0sUViWqyOInFkyyKxK0Ril4HE6oGRT+G4UrTzBe0m3VSFUdl5iIlk42fSOzems5hZj8XVAlc+Q4wNL0PsTE+V0V1idQBQsABBao2iV23VIuUG2iyyZ1uzilUoAprvQ4lNEiayHogbewF5pyWv+AgvPjTVC4RRHQEqLzLpod5/eAbShfgbMwPMPH2Pye2vPtLzz9pptj2hatyrWBgcAx909YqtD8CWiGBbIoZtiQQ2JVrrA7IkEgXrI1awPiIF60NQp2nOYpG3MOQsFvmCvpDFgubx0bmkoGyTeSSfzEnyAjk1KftLoWGdeHnmkzovO2uBPmcqghsOokXcEUrcCMirBpfIe2yDDtcXiVVgWweKyD4bC9dmJpEzMBTHGD8iernly60fWj2qQt9eMSttHjkB3Go2BdQ33NqQWASDGyBnuFOp+UCJiQnOsna9+1czBdQ+IG/ePtBFdokybIh5AaB/CKN/BKN/DKN/ok7+KnMVKssAVJLxqCRSlx8TcuQvP7klh/zyQXEQ1ht3NfPW5bxJD7k+VnM85uf2GisSQrKMPzlehm4jEd1qV2oOZ13QBspBBwoky6ZhkYfZDOTP56owc50+8Nm85dA5fo0y7BRJlWUWdqkeLZdc9w33yZ3HJO0lDeJ4dV/OSaNCZoDmDmCiCmGiimCiimGiapQCEmXt2goMJiiBNsdtEIMJypzNcRtUHjmY5ywem0HJwQWVyAT8xUQuKIW7LG41AKQdYP46J8eCyUxsVnCoSp171b6yCUsPhQTNxx0Szbt4ooXCNyMROJnIkhd24adn8TYGs3xlINIX8wSy0Wzi2XuTm1guBRe0YekJjM5YsgKKuX3krNFCSg+ibh65tgW11/gPGipd15VqY0yu82U5G3YAtRrA6BLC6BLB6BKrowuEIYIiX3PoAmFIpIAhoQKGCOptzdY9hhJPGGAW43jBIRgs6dEMwUy85/WOmbJ33iSipz3JYHoMxQ4mPXU86Z/6Q5uBHPXgQMS7GRlw0IQdQMisUOIoEkgJWH0dLPWsU2xQSYy26fGZAQYPwOvCAY9FElE8chaSgJkHQGYYj/Fvs33BEp8uExbMgCNH6AtqZolhJJIyTsV4AsBGCMNGBMNGgydIrlPXwfGkRRoITwTFoOaQBsITQbWmOaRRKqEGIQ3uhpH3wvB5w+XyxkxLIFY4PVYIS63pKnJZuFAoV2xD5MFlAC3uCc7LPRiL4KxjzNGBXLotI6/oFhM33pVZUsUDQapIyRaGi2KVM8pzuEfHMOGBgTVwgkjlzhIsQjORHpfZz6WoSFCYiYMogrpMYgwC1LgPI0wAI0wII0ykjjAIjrQIA+FIooAjsQKORAo4EirgCHTz/iyOcAhGdBsYwch7d/QIxpcxX3w5JS2lbvT8OBNrq0mBJOnZ0Zw3b1sWK8ykm2A5OwjEn49BIpbPhJuX3ACX8KuIG4MeZDYGaX2QoQ9yCmC4pByIxsWaLjZFt+Hpl1/v4H75g7iUwXfenrTAUFfoaOcJetJDWTE+A1QAHuGlYzwYj3wYjwIYj0IYjxqgQmDCFZSLmYMwhClaCIOAKlEAqlgBqCIFoFJYgIn5j2aBisNg8rHZcwwmv75zbv5LuSAQv2Gb69AwoKIS1qwLb7rCJLxgoRyi9pcuUhg5ktl5ogGpcPeZyMwjk4MnWhKbQj42mRkjXXGQpS7AzoqGZj2HEU4SwLzPA2CuMQAz00sFV/elSUDDqJBVGGRBTgRyJrsw9Xkw9fkw9QUw9YXq1AcRnKDAyRz1QQSXKBBcrEBwCmk3MJcbTnD+LMFxoE+Eahy6A1zULcYBRlgLaFjdBJzRJi6Xl0V5qKp+P5ljWJbbFiKKqCWKJfx5UjAjmbMETfegEWJriVMt8R+KEfhgfWhYw0rwwVbdBtaS6zmlJsr9OkvL3UFSvXOGjCM9fRepf/ocoSUoJCFmCIAIPJgIfJgIApgIGoZANI8rKP8wxx0QQzg4Q7TcASlfQU5/PnfgbiaF6tQKwUoKK8cUIpYghugzv8uvE+OACFQZxeZ6VlSSnyWNvldf7SbDEzorYSK+lwBavg4Gh3AU/SQKhLeYBIumkfdMzulz1gjWAwWJeA4sjkZ2sIPGrAOrLhdWXR6sunxYdQXqqgtSQ4Ls3XOqCzLNBWmy+aoLt5UxUxlXQ/w80DOaC1JDPlcNzWguaPrGxZUOP3My9yo215LknZLwdQWvYzFfOfBOiXqnsEpaTo5y0VrWYA1S4ErERPK6IsjLwDsFX4Jg4fPRlsAQYZ0CynEHluMuLMc9WI77sBxvJD8kxQWpa+e0BST5BYll57QFFA8J1S9McMkf45Kfn490RlkoZMhQCGuEJD8/n+eMsoAkP7/I04yygER/0nv0EDnO60LMNxJmNAlr1QisPxCPN57R0MJXsVt4WLaFT0FZILaDgt6BBb0LC3oPFvS+uqBXMQtUZtKwIHbcHsDMAVxo89Pszch5hXwCChksIaHt40Lbw4W2iwttQQa5OUGPvP+EL5lnhDny/gX1o2dEN2f1PayB8CRplo/LaDw41MJnBSyQyUEh7cBC2oWFtAcL6UasE3Hwvi2hVm38mJWH5qhNSQZItn2X08Jwv632p/s1nVRy7NimY+hXGvvif+WQvx5BiG4/6cT/Af7A3VDX1QEA
```
</details>

### Operating System

Android

**Comment by metablaster** [comment]
This issues seem to have been fixed, you might want to update your game.
https://github.com/yairm210/Unciv/issues/12575

**Comment by LyzN16** [comment]
I still get the same crash error on my game and I already updated

6 Ara 2024 Cum 14:02 tarihinde metablaster ***@***.***> şunu
yazdı:

**Comment by yairm210** [comment]
Copy of #12575
