### ISSUE TITLE
Modding Bug: `[+1] Movement` doesn't accept `<when adjacent to a [mapUnitFilter] unit>`

### ISSUE THREAD

**Issue by AceHank** [yairm210/Unciv#12798]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Game Version

4.15.2

### Describe the bug

This one is a quick report, it's as the title said. I didn't do extensive testing, just simple `"[+1] Movement <when adjacent to a [Favourable Wind] unit>",` Favourable Wind being a status, and it didn't work. Also in case it matters, I put the unique in UnitTypes.json,

Thank you very much!

### Steps to Reproduce

1. Give `"[+1] Movement <when adjacent to a [Favourable Wind] unit>",` to a unit
2. See error

### Screenshots

![image](https://github.com/user-attachments/assets/8e7632e1-10fd-4ee2-bdd0-3cb8a5dc7a68)
Cleric has the Favourable Wind status

![image](https://github.com/user-attachments/assets/498d2826-70a1-4239-8a4d-0a4801da229f)
Priest whose adjacent to Cleric (with Favourable Wind) move is still at 2/2

### Operating System

Windows

### Additional Information

I've also checked Priest's movement the next turn with same result.

**Comment by AceHank** [comment]
After some more testing, it worked fine if I use a tag instead of status name.
`"[+1] Movement <when adjacent to a [Swift] unit>"`, with Swift is a tag inside Favourable Wind.
![image](https://github.com/user-attachments/assets/3dba5399-bbbd-4a87-a623-7ec5d706dfaf)

I guess it's solved for me, but, devs please decide when to close this thread.

Thank you for the great work!

**Comment by yairm210** [comment]
I'm pretty sure this was already solved a while back

**Comment by AceHank** [comment]
> I'm pretty sure this was already solved a while back

After quick test yes, it's working fine with promotion name as of 4.15.13.

Thank you Devs!

**Comment by AceHank** [comment]
> I'm pretty sure this was already solved a while back

After quick test, as of 4.15.13, this still doesn't work for Status. I still need to use a tag inside a status. But for Promotion, it's working perfectly fine.

**Comment by yairm210** [comment]
Can you send me a save file and what to change in the mod?

**Comment by AceHank** [comment]
[Status Tag.zip](https://github.com/user-attachments/files/19003584/Status.Tag.zip)

Uses Epic of Fantasy and EoF Mages, should be the same mods used when you do the status view.

The save file is what worked, to make it doesn't work, change the UnitTypes.json, find `Favourable Wind Aura` and remove the Aura, making it only `Favourable Wind`, which is the status name.

Favourable Wind is only accessible with Cleric Aeromancy I

**Comment by yairm210** [comment]
Found the source, will enter next version

BTW, globalUniques also contains unit uniques, so effects for all unit types can go there
https://yairm210.github.io/Unciv/Modders/Mod-file-structure/5-Miscellaneous-JSON-files/#globaluniquesjson

**Comment by AceHank** [comment]
> Found the source, will enter next version
> 
> BTW, globalUniques also contains unit uniques, so effects for all unit types can go there https://yairm210.github.io/Unciv/Modders/Mod-file-structure/5-Miscellaneous-JSON-files/#globaluniquesjson

What, since when, so you're saying, if an effect affects ALL unit types, it can just go in GlobalUniques with one line? Thanks!

**Comment by yairm210** [comment]
Since 1 month ago, if **you** were not aware then probably other modders also aren't aware
Can you check that it works as expected? If yes, I'll post on Discord about this

**Comment by AceHank** [comment]
> Since 1 month ago, if **you** were not aware then probably other modders also aren't aware Can you check that it works as expected? If yes, I'll post on Discord about this

Yeah it worked fine! I've deleted all `Favourable Wind Aura` line in UnitTypes, and moved it to GlobalUniques, it still works.

Thanks for the great work!
