### ISSUE TITLE
Unlimited manufactories

### ISSUE THREAD

**Issue by TheEXAM** [yairm210/Unciv#2077]
**Describe the bug**
Great engineers can keep creating manufactories without disappearing.

**To Reproduce**
Spawn a great engineer and make it create a manufactory. It will not disappear.

**Expected behavior**
I'm pretty sure that great persons are supposed to disappear once they have been ordered to use their special ability.

**Screenshots**
![Screenshot_2020-03-04-15-08-46](https://user-images.githubusercontent.com/61744611/75859604-44df8b80-5e35-11ea-8849-f4b791e7fb54.png)
![Screenshot_2020-03-04-15-08-37](https://user-images.githubusercontent.com/61744611/75859618-49a43f80-5e35-11ea-9f21-6ec7df86b84a.png)
![Screenshot_2020-03-04-15-06-10](https://user-images.githubusercontent.com/61744611/75859627-4c9f3000-5e35-11ea-8122-ff526f576d08.png)

**Additional context**
I've just recently updated the game. I don't know if the same can happen if I order them to hurry wonders, or if it's the same as well with other great persons.

**Comment by hayounav** [comment]
Isn't this the bug that was reported in #2060 and resolved in PR #2062 ?
Are you on the latest version (3.6.5)?

**Comment by Dre4mslayer** [comment]
This bug is still occurring, if you load a save game and get a great person on the turn you saved, the scientist/engineer/artist/merchant will continuously be able to plop down special tiles until you order them to use their other designated special ability.

**Comment by TheEXAM** [comment]
> Isn't this the bug that was reported in #2060 and resolved in PR #2062 ?
> Are you on the latest version (3.6.5)?

Yes, as I have stated, I have just recently updated the game to its latest.

**Comment by hayounav** [comment]
I'm sorry, I didn't notice you mentioned that.
Do you have a save file in which I could use to try to reproduce this? I just tried with the save file from #2060 (https://github.com/yairm210/Unciv/files/4277861/Persia.-.117.turns.txt), and it seems to work correctly.

**Comment by yairm210** [comment]
This HAS been solved, and so the question of which version you're on is critical. Not everyone has the same 'latest'. What version are you on?

**Comment by TheEXAM** [comment]
> This HAS been solved, and so the question of which version you're on is critical. Not everyone has the same 'latest'. What version are you on?

**Was** on version 3.6.3 (patch 1) when this occured.

**Comment by Dre4mslayer** [comment]
I'm on version 3.6.5, still having this issue

**Comment by yairm210** [comment]
@Dre4mslayer Not scientifically possible!

**Comment by JackRainy** [comment]
I have tried to reproduce it and it works for me. It seems to be fixed.
@TheEXAM , @Dre4mslayer , do you have a saved game to reproduce it?

**Comment by yairm210** [comment]
This was solved a while back, closing =)
