### ISSUE TITLE
Let the cities change their appearance according to the eras of the game

### ISSUE THREAD

**Issue by wilsoncp8991** [yairm210/Unciv#3143]
Suggestion: Let the cities change their appearance according to the eras of the game, for example cities with medieval appearance for a civilization that is in the medieval era, industrial appearance in the industrial age, etc. Those details would greatly enhance the visual experience in the game ...

**Comment by yairm210** [comment]
For this, what were missing is actually the art!
We need a city image for each era.
I'm not an artist, so I can't really do much with this

**Comment by natrius** [comment]
Its to find there, am i correct? 
Unciv/android/Images/TileSets/FantasyHex/Tiles/

all City.png and so on?

**Comment by chriscr2** [comment]
I have tried to do it, I even installed tools to make and present them but I don't understand how they are done 
I will see some tutorials to be able to do and present them :)

**Comment by yairm210** [comment]
Yup, we need images like City.png (28x32 px) for each era

**Comment by yairm210** [comment]
Done, we currently have images for the first 3 eras

**Comment by wilsoncp8991** [comment]
Did you complete all the images for each era? or are they still missing?

**Comment by yairm210** [comment]
Still missing actual images, but the mechanism is up and working
