### ISSUE TITLE
Crash at load on Mac OSX with OpenJDK11 after changing resolution

### ISSUE THREAD

**Issue by MRigal** [yairm210/Unciv#3522]
**Describe the bug**
It crashes when starting the game via `java -jar unciv.jar`. After one resizes the window and/or changes the resolution to something other (I tested only higher) than the default 900*600 It is only starting the smiley shortly and then crashing. "DesktopLauncher" is crashing too.

**To Reproduce**
Modify the resolution and close the game. Next time it will crash, I always need to delete the GameSettings.json (or remove the windowState key from the json file to get it started again

**Expected behavior**
I guess it should not happen

**Additional context**
I have version 3.12.7-patch1. Here is the output
```
Error in LSRegisterURL: -10811
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.lwjgl.LWJGLUtil$3 (file:/Users/foobar/Documents/Unciv.jar) to method java.lang.ClassLoader.findLibrary(java.lang.String)
WARNING: Please consider reporting this to the maintainers of org.lwjgl.LWJGLUtil$3
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
AL lib: (EE) ca_open_playback: AudioUnitInitialize failed
Loading ruleset - 235ms
Loading percent complete of languages - 1ms
2021-01-12 11:40:37.903 java[70531:1012115] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'NSWindow drag regions should only be invalidated on the Main Thread!'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fff204fc6af __exceptionPreprocess + 242
	1   libobjc.A.dylib                     0x00007fff202343c9 objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff20524a9a -[NSException raise] + 9
	3   AppKit                              0x00007fff22cc88a0 -[NSWindow(NSWindow_Theme) _postWindowNeedsToResetDragMarginsUnlessPostingDisabled] + 321
	4   AppKit                              0x00007fff22cf0c1b -[NSThemeFrame setStyleMask:] + 142
	5   AppKit                              0x00007fff22cf09b1 __25-[NSWindow setStyleMask:]_block_invoke + 2057
	6   AppKit                              0x00007fff22cf014e NSPerformVisuallyAtomicChange + 132
	7   AppKit                              0x00007fff22cf005b -[NSWindow setStyleMask:] + 170
	8   liblwjgl.dylib                      0x00000001367fbcca Java_org_lwjgl_opengl_MacOSXDisplay_nSetResizable + 90
	9   ???                                 0x0000000110e1b330 0x0 + 4578194224
)
libc++abi.dylib: terminating with uncaught exception of type NSException
Abort trap: 6
```

**Comment by yairm210** [comment]
Hm
Can't see anything obvious that would cause this and I don't have a mac so can't really debug this :/
What happens if you resize the window?

**Comment by MRigal** [comment]
Resizing the window is fine, changing the resolution also.

But somehow it crashes when trying to restore the `windowState` stored in `GameSettings.json`. Always. 

In the meanwhile I got used to remove the `windowState` key from the file instead of deleting the file, to avoid to restore all the rest.

I really have no clue also why it is behaving this way. The problem might be on the JDK side. 

Maybe a work-around would to make configurable the fact to save the window state, disabled by default?

**Comment by yairm210** [comment]
Or we could detect if it's running on a Mac and only disable it there

**Comment by MRigal** [comment]
I wish some other Mac user could see and confirm (or not) the error. It might be only related to the version 11 and/or only to JDK11...

Sorry I meant that saving the window state should be enabled by default, but could be disabled to prevent this kind of crash...

**Comment by IISAKNIFE** [comment]
Just installed default version of Java on my Mojave Mac, and ran into this exact same issue. The fix to get it launched worked as well

**Comment by yairm210** [comment]
We recently made some changes to the game setup that also relate to the resizing, can anyone here check if from 3.13.8 this is solved?

**Comment by Mohre** [comment]
Hi. thanks a lot for your efforts.
I downloaded the last unciv.jar file (version 3.11.13) and the problem still exists.

**Comment by robichaudc** [comment]
Seeing the same issue, Macbook Pro Catalina 10.15.7. I am building with Android Studio and it loaded the first time, but when I plugged in my external monitor it started crashing

I ended up deleting android/assets/GameSettings.json and that seems to have fixed it for now

**Comment by SomeTroglodyte** [comment]
Sounds interesting, as I suspect that windowstate restore might have been my fault - have you tried running under [a different JRE](https://adoptopenjdk.net/releases.html)?

Or... (@robichaudc)
```
            try {
                Gdx.graphics.setWindowedMode(settings.windowState.width, settings.windowState.height)
            } catch (ignored:Exception) {}
```
for UncivGame.kt line 126?

**Comment by robichaudc** [comment]
I'm not sure if this is related but after the latest back-merge I am getting an immediate crash of the app right after startup (with or without the code commented out mentioned above). Also tried using different java version as you suggested @SomeTroglodyte but it seems to have no effect. Posting in case anyone else is running into the same issue

Here is the error logs:
```
2021-04-16T01:47:29.577-0400 [DEBUG] [org.gradle.process.internal.DefaultExecHandle] Changing state to: STARTED
2021-04-16T01:47:29.577-0400 [INFO] [org.gradle.process.internal.DefaultExecHandle] Successfully started process 'command '/Applications/Android Studio Preview.app/Contents/jre/jdk/Contents/Home/bin/java''
2021-04-16T01:47:29.577-0400 [DEBUG] [org.gradle.process.internal.ExecHandleRunner] waiting until streams are handled...
2021-04-16T01:47:30.230-0400 [QUIET] [system.out] Packing textures - 288ms
2021-04-16T01:47:30.919-0400 [ERROR] [system.err] Error in LSRegisterURL: -10811
2021-04-16T01:47:33.404-0400 [ERROR] [system.err] WARNING: An illegal reflective access operation has occurred
An illegal reflective access operation has occurred

2021-04-16T01:47:33.404-0400 [ERROR] [system.err] WARNING: Illegal reflective access by org.lwjgl.LWJGLUtil$3 (file:/Users/chrisrobichaud/.gradle/caches/modules-2/files-2.1/org.lwjgl.lwjgl/lwjgl/2.9.3/3df168ac74e4a8c96562cdff24ad352e255bf89c/lwjgl-2.9.3.jar) to method java.lang.ClassLoader.findLibrary(java.lang.String)
Illegal reflective access by org.lwjgl.LWJGLUtil$3 (file:/Users/chrisrobichaud/.gradle/caches/modules-2/files-2.1/org.lwjgl.lwjgl/lwjgl/2.9.3/3df168ac74e4a8c96562cdff24ad352e255bf89c/lwjgl-2.9.3.jar) to method java.lang.ClassLoader.findLibrary(java.lang.String)

2021-04-16T01:47:33.404-0400 [ERROR] [system.err] WARNING: Please consider reporting this to the maintainers of org.lwjgl.LWJGLUtil$3
Please consider reporting this to the maintainers of org.lwjgl.LWJGLUtil$3

2021-04-16T01:47:33.404-0400 [ERROR] [system.err] WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
Use --illegal-access=warn to enable warnings of further illegal reflective access operations

2021-04-16T01:47:33.404-0400 [ERROR] [system.err] WARNING: All illegal access operations will be denied in a future release
All illegal access operations will be denied in a future release

2021-04-16T01:47:33.602-0400 [QUIET] [system.out] #
2021-04-16T01:47:33.602-0400 [QUIET] [system.out] # A fatal error has been detected by the Java Runtime Environment:
2021-04-16T01:47:33.602-0400 [QUIET] [system.out] #
2021-04-16T01:47:33.602-0400 [QUIET] [system.out] #  SIGILL (0x4) at pc=0x00007fff36fedabc, pid=74154, tid=125955
2021-04-16T01:47:33.603-0400 [QUIET] [system.out] #
2021-04-16T01:47:33.603-0400 [QUIET] [system.out] # JRE version: OpenJDK Runtime Environment (11.0.9.1) (build 11.0.9.1+0-b77-7246554)
2021-04-16T01:47:33.603-0400 [QUIET] [system.out] # Java VM: OpenJDK 64-Bit Server VM (11.0.9.1+0-b77-7246554, mixed mode, tiered, compressed oops, g1 gc, bsd-amd64)
2021-04-16T01:47:33.603-0400 [QUIET] [system.out] # Problematic frame:
2021-04-16T01:47:33.603-0400 [QUIET] [system.out] # C  [AppKit+0x3e5abc]  -[NSOpenGLContext setView:]+0xe5
2021-04-16T01:47:33.604-0400 [QUIET] [system.out] #
2021-04-16T01:47:33.604-0400 [QUIET] [system.out] # No core dump will be written. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
2021-04-16T01:47:33.604-0400 [QUIET] [system.out] #
2021-04-16T01:47:33.604-0400 [QUIET] [system.out] # An error report file with more information is saved as:
2021-04-16T01:47:33.604-0400 [QUIET] [system.out] # /Users/chrisrobichaud/repos/github_robichaudc/Unciv/android/assets/hs_err_pid74154.log
2021-04-16T01:47:33.667-0400 [QUIET] [system.out] #
2021-04-16T01:47:33.667-0400 [QUIET] [system.out] # If you would like to submit a bug report, please visit:
2021-04-16T01:47:33.667-0400 [QUIET] [system.out] #   https://bugreport.java.com/bugreport/crash.jsp
2021-04-16T01:47:33.667-0400 [QUIET] [system.out] # The crash happened outside the Java Virtual Machine in native code.
2021-04-16T01:47:33.668-0400 [QUIET] [system.out] # See problematic frame for where to report the bug.
2021-04-16T01:47:33.668-0400 [QUIET] [system.out] #
2021-04-16T01:47:33.672-0400 [DEBUG] [org.gradle.process.internal.DefaultExecHandle] Changing state to: FAILED
2021-04-16T01:47:33.672-0400 [DEBUG] [org.gradle.process.internal.DefaultExecHandle] Process 'command '/Applications/Android Studio Preview.app/Contents/jre/jdk/Contents/Home/bin/java'' finished with exit value 134 (state: FAILED)
```

**Comment by SomeTroglodyte** [comment]
"LSRegisterURL" seems related to the Discord Api on macs, the five fat warnings are known to pop with libGdx and Java 11-14, the rest is just one exception where "AppKit" proves it's thrown within an Apple piece of code and "NSOpenGLContext" raises the slight suspicion it's got something to do with displaying something - could be anything from incompatible libraries and nothing to do with Unciv to timing issues coaxing Unciv to paint stuff at the wrong time or in a wrong thread. Search hits like [this one](https://bugs.openjdk.java.net/browse/JDK-8255592) might support the "Unciv is completely innocent" theory...

Anything more interesting in that hs_err_pid74154.log (usually there isn't)?

Without a mac, can't say or investigate. If I had one, I'd set breakpoints at the start of DesktopLauncher.main and the LoadingScreen() call in UncivGame, verify it's happening in between, then F8-single step it to identify the line, see if it's something you can step into and so on until something catches the eye... If you can even get to the first breakpoint.

**Comment by yairm210** [comment]
https://github.com/yairm210/Unciv/pull/4042
