### ISSUE TITLE
`TileSetConfig` not set on first load.

### ISSUE THREAD

**Issue by will-ca** [yairm210/Unciv#5834]
With `./gradlew desktop:run`.

Freshly downloaded 5Hex is looking way darker in-game than the images suggest it should?

![image](https://user-images.githubusercontent.com/37680486/146807492-188204c4-a469-4b14-aae7-b967aab3a245.png)

Feels like all the RGBs are squared.

The `game.png` seems fine:
![game](https://user-images.githubusercontent.com/37680486/146807816-8d338fd9-8d78-452f-bf41-79ea28a29a89.png)

After a restart it's fine:

![image](https://user-images.githubusercontent.com/37680486/146807944-1c152127-d74a-432b-a1a2-d63cd8fac0ba.png)

Not sure how to reproduce… But I think it's happened before too, but with a JAR.

And Pix5, on Android:

![image](https://user-images.githubusercontent.com/37680486/146980995-112dc8b6-74b2-4753-a700-3af38f3a57e0.png)

How it's supposed to look:

![image](https://user-images.githubusercontent.com/37680486/146981183-caae7193-1ea8-4cb7-a827-0282f808845c.png)

---

Yeah. This is supposed to have the same colours as FantasyHex:

![image](https://user-images.githubusercontent.com/37680486/146993287-1fe1a91c-1c7f-4ca9-8b8b-7e7a76644fef.png)

**Comment by xlenstra** [comment]
If I'm not mistaken, this has been brought up before and the conclusion was that this was the result of the tileset trying to override the default fantasyHex tileset

**Comment by will-ca** [comment]
5Hex doesn't do that AFAICT thoiugh, and this is specifically after Pix5 was updated (https://github.com/AdityaMH/Pix5-Tileset/pull/2) to no longer do it, nor does the tile variants example.

**Comment by AdityaMH** [comment]
> 5Hex doesn't do that AFAICT thoiugh, and this is specifically after Pix5 was updated ([AdityaMH/Pix5-Tileset#2](https://github.com/AdityaMH/Pix5-Tileset/pull/2)) to no longer do it, nor does the tile variants example.

I'm just download strike from github website, place it on folder, start game, greeny occur, delete from mod manager, restart, fixed automatically.

**Comment by AdityaMH** [comment]
> If I'm not mistaken, this has been brought up before and the conclusion was that this was the result of the tileset trying to override the default fantasyHex tileset

Yeah, but @will-ca suggest me to not override.

**Comment by will-ca** [comment]
Oh! You know what? It's probably not due to overriding FantasyHex; It's probably due to `TileSetConfig().useColorAsBaseTerrain` being left at `true` (which would also happen if a tileset tries to override not FantasyHex, but Default).

**Comment by AdityaMH** [comment]
> Oh! You know what? It's probably not due to overriding FantasyHex; It's probably due to `TileSetConfig().useColorAsBaseTerrain` being left at `true` (which would also happen if a tileset tries to override not FantasyHex, but Default).

But i'm set it 'false'

**Comment by will-ca** [comment]
@AdityaMH Not about Pix5. I mean the config probably isn't being properly loaded on first mod download.

**Comment by yairm210** [comment]
@will-ca Was this solved by your change?

**Comment by will-ca** [comment]
> @will-ca Was this solved by your change?

I don't think I touched anything that would affect this… Test on latest `master` shows it still happens:

![image](https://user-images.githubusercontent.com/37680486/150692605-ec712301-c072-4276-8c9d-8e9daf800b8e.png)

**Comment by will-ca** [comment]
It's not just the colours, but the entire `TileSetConfig` that isn't being updated on first use of the mod. E.G. `tileScale`:

![image](https://user-images.githubusercontent.com/37680486/150702948-93259b1b-7a2d-4463-8ca6-da160ef26447.png)

And somewhat relatedly (but a different issue), when you delete the active tileset, it doesn't automatically switch over to another one:

![image](https://user-images.githubusercontent.com/37680486/150702985-79e4120e-9d16-45d0-b381-9115d922afd1.png)

**Comment by yairm210** [comment]
IS this still relevant?

**Comment by yairm210** [comment]
Guess not
