### ISSUE TITLE
Multiplayer Server Bugs

### ISSUE THREAD

**Issue by touhidurrr** [yairm210/Unciv#6471]
**Platform**
Android, Linux

**Version**
4.0.2

**Describe the bug**
1. Hostnames Like `uncivserver.xyz` doesn’t work
2. Hostname's like `uncivserver.xyz:80` doesn’t work either
3. Redirects doesn’t work. (Automatic Redirection to HTTPS)

**To Reproduce**
to reproduce 1, 2 & 3 at the same time just try setting the hostname to `uncivserver.xyz:80`

**Recommended Solutions:**
1. If a hostname `(e.g. uncivserver.xyz)` is provided instead of an IP (X.X.X.X), omit port unless provided
2. Enable redirections
3. Use a library that supports HTTP & HTTPS

**Comment by touhidurrr** [comment]
Alongside aforementioned issues, on Android, it doesn’t work at all. To test this I run the Server from Termux and even though `http://0.0.0.0:8080/isalive` worked fine on browser when I inputted `0.0.0.0` or `0.0.0.0:8080` it doesn’t work on unciv.
Tried `localhost` and `127.0.0.1` in place of `0.0.0.0`, although working on Browser both doesn’t work in Android either.

**Comment by yairm210** [comment]
Not a 'bug' per se but solved in 6315a16d - will roll out in this version :)
I managed to create a multiplayer game on uncivserver.xyz so it should work ;)

**Comment by touhidurrr** [comment]
Still facing the issue...
```java
**Platform:** Desktop
**Version:** 4.0.3
**Rulesets:** [Civ V - Vanilla, RekMOD, Civ V - Gods & Kings, 5Hex Tileset]
**Last Screen:** `com.unciv.MainMenuScreen`

--------------------------------

OS: Linux (arm, 5.10.103-v7+)
	Raspbian GNU/Linux 11 (bullseye)
Java: Temurin 25.322-b06
	Max Memory: 224 MB


--------------------------------


**Message:**
\```
java.net.MalformedURLException: no protocol: uncivserver.xyz/isalive
	at java.net.URL.<init>(URL.java:611)
	at java.net.URL.<init>(URL.java:508)
	at java.net.URL.<init>(URL.java:457)
	at com.unciv.ui.worldscreen.mainmenu.OptionsPopup$SimpleHttp.sendRequest(OptionsPopup.kt:315)
	at com.unciv.ui.worldscreen.mainmenu.OptionsPopup$SimpleHttp.sendGetRequest(OptionsPopup.kt:311)
	at com.unciv.ui.worldscreen.mainmenu.OptionsPopup.successfullyConnectedToServer(OptionsPopup.kt:345)
	at com.unciv.ui.worldscreen.mainmenu.OptionsPopup$getMultiplayerTab$1$6.invoke(OptionsPopup.kt:290)
	at com.unciv.ui.worldscreen.mainmenu.OptionsPopup$getMultiplayerTab$1$6.invoke(OptionsPopup.kt:284)
	at com.unciv.ui.utils.ExtensionFunctionsKt$onClick$1.invoke(ExtensionFunctions.kt:74)
	at com.unciv.ui.utils.ExtensionFunctionsKt$onClick$1.invoke(ExtensionFunctions.kt:74)
	at com.unciv.ui.utils.ExtensionFunctionsKt$onClickEvent$1.clicked(ExtensionFunctions.kt:67)
	at com.badlogic.gdx.scenes.scene2d.utils.ClickListener.touchUp(ClickListener.java:88)
	at com.badlogic.gdx.scenes.scene2d.InputListener.handle(InputListener.java:71)
	at com.badlogic.gdx.scenes.scene2d.Stage.touchUp(Stage.java:355)
	at com.unciv.CrashHandlingStage.access$touchUp$s80204510(CrashHandlingStage.kt:10)
	at com.unciv.CrashHandlingStage$touchUp$1.invoke(CrashHandlingStage.kt:24)
	at com.unciv.CrashHandlingStage$touchUp$1.invoke(CrashHandlingStage.kt:24)
	at com.unciv.ui.utils.ExtensionFunctionsKt$wrapCrashHandling$1.invoke(ExtensionFunctions.kt:329)
	at com.unciv.CrashHandlingStage.touchUp(CrashHandlingStage.kt:24)
	at com.badlogic.gdx.InputEventQueue.drain(InputEventQueue.java:70)
	at com.badlogic.gdx.backends.lwjgl3.DefaultLwjgl3Input.update(DefaultLwjgl3Input.java:189)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Window.update(Lwjgl3Window.java:394)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.loop(Lwjgl3Application.java:143)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:116)
	at com.unciv.app.desktop.DesktopLauncher.main(DesktopLauncher.kt:59)

\```

**Save Mods:**
\```
No mod data: kotlin.UninitializedPropertyAccessException: lateinit property gameInfo has not been initialized
\```

**Save Data:**
<details><summary>Show Saved Game</summary>

\```
No save data: kotlin.UninitializedPropertyAccessException: lateinit property gameInfo has not been initialized
\```
</details>
```

**Comment by touhidurrr** [comment]
Oh It seems like I need to Put `https://uncivserver.xyz`
My Bad
It works fine if I put `https://uncivserver.xyz`

**Comment by touhidurrr** [comment]
@yairm210 now that I think about reported bug didn’t go away. Game still crashes on the aforementioned scenario's.
![Screenshot_2022-04-02-19-47-29-27_572064f74bd5f9fa804b05334aa4f912](https://user-images.githubusercontent.com/46617994/161386268-e0761272-fb1a-4c64-b42e-4ed660d0d79a.jpg)
