### ISSUE TITLE
Should `experimental` releases be marked as a Pre-Release?

### ISSUE THREAD

**Issue by Botspot** [yairm210/Unciv#7175]
Unciv is in [the Pi-Apps store](https://github.com/Botspot/pi-apps) and whenever a new release comes out, we get notified by a GitHub Actions script to update the app.
See this in action here: https://github.com/Botspot/pi-apps/pull/1977
The past few releases on this repo have included the word **`experimental`**, and I was wondering if these releases were intended to be production-ready for non-technical users. If you want Pi-Apps to avoid using these releases, then please mark them as a "Pre-Release". (GitHub has a handy checkbox for this)

**Comment by yairm210** [comment]
Oh sweet!
Thanks for that, we're still figuring out how we want to handle experimental releases ourselves, so we'll keep this in mind :)
Do you have a preferred badge with which to link to you from the readme?

**Comment by Botspot** [comment]
> Do you have a preferred badge with which to link to you from the readme?

We sure do!
[![badge](https://github.com/Botspot/pi-apps/blob/master/icons/badge.png?raw=true)](https://github.com/Botspot/pi-apps)  
```
[![pi-apps badge](https://github.com/Botspot/pi-apps/blob/master/icons/badge.png?raw=true)](https://github.com/Botspot/pi-apps)  
```

**Comment by heipizhu4** [comment]
Resolved by d14ec04ef8cdea59b2b9472351853bf443ed6115 , so should this issue be closed now?

**Comment by yairm210** [comment]
The main issue, which is having experimental releases, is not yet resolved

**Comment by yairm210** [comment]
Non-version releases have been Github prereleases for a while now, forgot that this issue existed

**Comment by Botspot** [comment]
Did you decide against adding our badge to the README?

**Comment by yairm210** [comment]
Yes, now that we have 7 different distribution platforms, we've opted for the minimalistic vadges at the top of the readme for visual similarity and brevity
