### ISSUE TITLE
Auto build issue and suggestion

### ISSUE THREAD

**Issue by designbyian** [yairm210/UnCiv#875]
Love this project!

In the newest version cities which are set to produce resources (i.e. science) now switch to building military units every turn while at war. Super frustrating late game. I'm not sure if cities also switch to auto building non military when not at war, haven't tested.

While I'm on the subject, it would be amazing to have a setting flag to turn off the behavior where cities (almost) always auto start building military units after finishing a construction when at war. I understand the thinking behind the behavior but in actual practice it just means manually switching them to non military construction the majority of the time.

Many thanks for the great app :)

**Comment by yairm210** [comment]
Problem A that you mentioned is already fixed, rolling out in version 2.17.7
As for the second, I'll see what I can do

**Comment by designbyian** [comment]
In case you haven't already heard about it, Problem A still exists but is sporadic now. I have yet to see a pattern, only that cities set to "produce" occasionally revert to building on their own.

**Comment by yairm210** [comment]
If the production is USER SET then it will stay until changed.
If the production is AUTO SET then it will change when there's a better automation.
Not a bug.

**Comment by designbyian** [comment]
Production changes when user set, just not consistently. I've observed it multiple times in the latest version in play store.

**Comment by yairm210** [comment]
...Aha.
I'll check.

**Comment by yairm210** [comment]
Apparently I forgot to SAVE whether the current construction is user set, so if you would close your game and reopen it, leading the game to load, that data would be lost and all constructions treated as auto-set 🙄 
Thanks for this, good catch! =D

**Comment by designbyian** [comment]
Ah, glad it was an easy fix!
